name: annora-lore
services:
  neo4j:
    container_name: lore-neo4j
    image: neo4j:5.18-community
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt Protocol
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - lore_neo4j_data:/data
      - lore_neo4j_logs:/logs
    restart: unless-stopped

  annora-lore:
    container_name: lore
    build: .
    ports:
      - "8000:8000"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: bolt://lore-neo4j:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}

  volumes:
    lore_neo4j_data:
    lore_neo4j_logs:
